language: node_js
node_js: "5"
# install dependencies
install:
  - npm install
  - ./node_modules/grunt-cli/bin/grunt default
  - cd py
  - pip install --user -e '.[all]'
  - cd ..
# run tests
script:
  - ./node_modules/grunt-cli/bin/grunt coverage
  - cd py
  - python setup.py test
  - cd ..
# no emails
notifications:
  email: false
# run with containers
sudo: false
