environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
      NODEJS_VERSION: "6.2.2"

    - PYTHON: "C:\\Python34-x64"
      NODEJS_VERSION: "6.2.2"

    - PYTHON: "C:\\Python35-x64"
      NODEJS_VERSION: "6.2.2"

install:
  # add python to PATH
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version
  # set node version
  - ps: "Install-Product node $env:NODEJS_VERSION"
  - node --version
  # install js packages
  - npm install
  - npm run-script compile
  # install python packages
  - python -m pip install --upgrade pip
  - cd py
  - python -m pip install -e .
  - cd ..

build: off

test_script:
  - npm run-script test
  - cd py
  - python -m pytest
  - cd ..

artifacts:
  - path: py\dist\*
